### PR TITLE
fix: Remove duplicate nodeselector in template

### LINKED ISSUE #633: Nodeselector is duplicated in Daemonset Template
**Describe the bug**
The deploy chart for Hubble + Retina has duplicate [NodeSelector](https://github.com/microsoft/retina/blob/cdc12eead953b2996b63706921b4d0caf496c026/deploy/hubble/manifests/controller/helm/retina/templates/agent/daemonset.yaml#L140)

```
Helm install failed for release kube-system/retina-source with chart retina@0.0.1+cdc12eead953: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 144: mapping key "nodeSelector" already defined at line 27
```

**To Reproduce**
Attempt to Helm install from Git

**Expected behavior**
Chart works as expected and installs

- OS: Amazon Linux
- Kubernetes Version: 1.28
- Host: EKS
- Retina Version: Git HEAD + v0.0.14

**Additional context**

### PR DESCRIPTION
**Pull request by whatnick**
# Description

Closes #633 

## Related Issue

If this pull request is related to any issue, please mention it here. Additionally, make sure that the issue is assigned to you before submitting this pull request.

## Checklist

- [ ] I have read the [contributing documentation](https://retina.sh/docs/contributing).
- [ ] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [ ] I have correctly attributed the author(s) of the code.
- [ ] I have tested the changes locally.
- [ ] I have followed the project's style guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Please add any relevant screenshots or GIFs to showcase the changes made.

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

**Review by nddq — DISMISSED** [review]
lgtm, thanks!

**Comment by nddq** [comment]
@whatnick please make sure that all commits are signed so we can get this in, thanks!

**Comment by whatnick** [comment]
> @microsoft-github-policy-service agree company="CSIRO"

**Comment by whatnick** [comment]
> @microsoft-github-policy-service agree company="CSIRO"

**Comment by whatnick** [comment]
> @whatnick please make sure that all commits are signed so we can get this in, thanks!

Signing the commit took a bit of rebase. Happy to reopen the small PR from a fresh branch if appropriate.

**Comment by whatnick** [comment]
Closed to clean up commit history

**Pull request closed without merging**
