### PR TITLE
chore(*): replace discontinued github.com/golang/mock with actively maintained go.uber.org/mock

### PR DESCRIPTION
**Pull request by hainenber**
# Description

- Replace discontinued `golang/mock` with a more actively maintained `go.uber.org/mock`.
- Add a missing refererence for generated go-generated mock file.

## Related Issue

N/A

## Checklist

- [x] I have read the [contributing documantation](https://retina.sh/docs/contributing).
- [x] I signed and signed-off the commits (`git commit -S -s ...`)
- [x] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have added tests, if applicable.

## Screenshots (if applicable)

Please add any relevant screenshots or GIFs to showcase the changes made.

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

**Review by timraymond — CHANGES_REQUESTED** [review]
This looks pretty good, but there's a lot of fmter noise. Could you align your fmter config and re-run it so that it preserves the stratification of stdlib, external dependencies, and intra-module dependencies?

**Comment by timraymond** [comment]
@hainenber btw, the fmter most of us use is https://github.com/mvdan/gofumpt, which I believe does this by default

**Comment by hainenber** [comment]
Fixed. Turns out I ran `gci` on the whole codebase instead of changed files :D

**Review by rbtr — APPROVED** [review]
seems reasonable to me, thanks 👍

**Review by timraymond — DISMISSED** [review]
LGTM 👍

**Comment by rbtr** [comment]
Hey @hainenber if you will resolve conflicts and sign, then I think we can get this merged

**Comment by hainenber** [comment]
merge conflict resolved :D

**Comment by rbtr** [comment]
Thanks @hainenber! Sorry one last thing - we require all commits to be cryptographically signed. I think maybe you had done this, but it was lost during an update. Can you re-sign them?

**Comment by hainenber** [comment]
I always sign off my commits by default though. Do I miss something?

image

**Comment by rbtr** [comment]
> I always sign off my commits by default though. Do I miss something?
> [...]
> Edit: Hmm, they're no longer verified. Let me re-sign them for that

Right, you've got the Signed-off-By already. But this is the extra bit I'm looking for:
image

This is a merge requirement given the low-level access that Retina has to the hosts 🙂

**Comment by hainenber** [comment]
Could be something I could work on as well :D

Anyhow, the commits are now signed with my key :D

**Review by rbtr — APPROVED** [review]
LGTM thanks!

**Pull request merged**
