### PR TITLE
feat(helm): Added support for affinity, readinessProbe and custom probes

### PR DESCRIPTION
**Pull request by gciria**
# Description

Added support for `affinity`, `readinessProbe` and `custom probes`.

## Checklist

- [x] I have read the [contributing documentation](https://retina.sh/docs/contributing).
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Affinity:
retina-affinity

Probes:
retina-probes

### CODE REVIEW

**Review by SRodi — COMMENTED** [review]
Hi @gciria, thanks for adding this support! Could you please rebase and resolve any conflicts?

**Review by SRodi — APPROVED** [review]
thanks for this work @gciria! I would suggest in future to create an issue to discuss your enhancements proposals, so that the rationale behind the change is clear for everyone and also the work item can be added and eventually accepted in [Retina Triage Board](https://github.com/orgs/microsoft/projects/1154)

**Review by ibezrukavyi — APPROVED** [review]

**Comment by SRodi** [comment]
@gciria can you sign your commit? https://retina.sh/docs/Contributing/developing#cryptographic-signing-of-commits

**Comment by gciria** [comment]
> thanks for this work @gciria! I would suggest in future to create an issue to discuss your enhancements proposals, so that the rationale behind the change is clear for everyone and also the work item can be added and eventually accepted in [Retina Triage Board](https://github.com/orgs/microsoft/projects/1154)
Sure @SRodi  ! Thanks for the feedback.

**Comment by gciria** [comment]
> @gciria can you sign your commit? https://retina.sh/docs/Contributing/developing#cryptographic-signing-of-commits

Commit signed. Thanks

**Pull request merged**
