### PR TITLE
fix: failed to initialize filter map

### PR DESCRIPTION
**Pull request by wenhuwang**
# Description

fixes: #153 

## Testing Done

1. Built amd64 image and deployed them in a K8s cluster
2. agent pod is up and running

### CODE REVIEW

**Review by anubhabMajumdar — APPROVED** [review]
Thanks for the change!

**Comment by rbtr** [comment]
@wenhuwang can you sign your commit please? `git commit -S -s --amend --no-edit && git push -f` should do it 🙂

**Comment by wenhuwang** [comment]
> @wenhuwang can you sign your commit please? `git commit -S -s --amend --no-edit && git push -f` should do it 🙂

@rbtr thank you, have done.

**Comment by rbtr** [comment]
Hey @wenhuwang, I see a signed commit now but there are other commits on the branch that are unsigned. Unfortunately those are still preventing merge. If you can squash to a single commit or sign them all, we can complete this 🙂

**Comment by wenhuwang** [comment]
@rbtr  hello，it should be fine now?

**Review by rbtr — APPROVED** [review]
reapproved

**Comment by rbtr** [comment]
thanks @wenhuwang! this will be in v0.0.5

**Pull request merged**
