### PR TITLE
fix: typo in drop_reason.c

### PR DESCRIPTION
**Pull request by eltociear**
lenth -> length

### CODE REVIEW

**Review by anubhabMajumdar — APPROVED** [review]

**Review by vakalapa — APPROVED** [review]

**Comment by rbtr** [comment]
@eltociear please amend your commit message so that it conforms to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
"fix: typo in drop_reason.c" or similar is sufficient

**Comment by anubhabMajumdar** [comment]
@eltociear The PR is ready to merge pending a verified commit. Can you kindly sign the commit cryptographically? In case you need it, adding some instruction - https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification ; thanks!

**Comment by eltociear** [comment]
please chech

**Comment by nddq** [comment]
can you sign your previous commit so we can merge this? Thanks!

**Pull request closed without merging**
